### ISSUE TITLE
4.2 dev upgrade fails

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-local_aws#56]
Upgrade from 3.11 -> 4.2dev

```
Exception - Undefined constant GuzzleHttp\Client::VERSION

[More information about this error](http://docs.moodle.org/311/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 136 of /local/aws/sdk/GuzzleHttp/functions.php: Error thrown
line 40 of /local/aws/sdk/Aws/Handler/GuzzleV6/GuzzleHandler.php: call to GuzzleHttp\default_user_agent()
line 87 of /local/aws/sdk/Aws/WrappedHttpHandler.php: call to Aws\Handler\GuzzleV6\GuzzleHandler->__invoke()
line 126 of /local/aws/sdk/Aws/ClientSideMonitoring/AbstractMonitoringMiddleware.php: call to Aws\WrappedHttpHandler->__invoke()
line 43 of /local/aws/sdk/Aws/S3/PermanentRedirectMiddleware.php: call to Aws\ClientSideMonitoring\AbstractMonitoringMiddleware->__invoke()
line 41 of /local/aws/sdk/Aws/S3/PutObjectUrlMiddleware.php: call to Aws\S3\PermanentRedirectMiddleware->__invoke()
line 126 of /local/aws/sdk/Aws/Middleware.php: call to Aws\S3\PutObjectUrlMiddleware->__invoke()
line 41 of /lib/guzzlehttp/promises/src/FulfilledPromise.php: call to Aws\Middleware::Aws\{closure}()
line 48 of /lib/guzzlehttp/promises/src/TaskQueue.php: call to GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
line 248 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\TaskQueue->run()
line 224 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitFn()
line 269 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
line 226 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitList()
line 62 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
line 58 of /local/aws/sdk/Aws/AwsClientTrait.php: call to GuzzleHttp\Promise\Promise->wait()
line 693 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\AwsClient->execute()
line 152 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\S3\StreamWrapper->openReadStream()
line 918 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\S3\StreamWrapper->Aws\S3\{closure}()
line 156 of /local/aws/sdk/Aws/S3/StreamWrapper.php: call to Aws\S3\StreamWrapper->boolCall()
line ? of unknownfile: call to Aws\S3\StreamWrapper->stream_open()
line 434 of /admin/tool/objectfs/classes/local/store/object_file_system.php: call to file_get_contents()
line 453 of /lib/filestorage/stored_file.php: call to tool_objectfs\local\store\object_file_system->get_content()
line 165 of /lib/db/upgrade.php: call to stored_file->get_content()
line 1890 of /lib/upgradelib.php: call to xmldb_main_upgrade()
line 527 of /admin/index.php: call to upgrade_core()
```

**Comment by aspark21** [comment]
aws sdk added PHP8.0 / 8.1 support 6 months ago - https://github.com/aws/aws-sdk-php/commit/af584e7188dba00d76b7ec2306ac69efa2ad8483 - need to be on > 3.235.7

So should "just" be a case of bumping the SDK

they don't seem to have dropped any backwards compatibility yet either in the most recent 3.261.2 - https://github.com/aws/aws-sdk-php/blob/master/.github/workflows/tests.yml#L19

**Comment by aspark21** [comment]
well it's more complicated than I hoped. I did try a higher version and still ran into the error.
Tracking through similar errors, it seems to happen when multiple versions of Guzzle are loaded. 
Sure enough, Guzzle was added in core a month ago - https://github.com/moodle/moodle/commit/7b150add4453ca470919f9fbd65d637a5ccc7c03
https://tracker.moodle.org/browse/MDL-76135

**Comment by brendanheywood** [comment]
I think we should cut a new stable version for 4.2 then

**Comment by aspark21** [comment]
FYI - I've logged this as WR402279

**Comment by sarahjcotton** [comment]
Is this fixed here: https://github.com/catalyst/moodle-local_aws/pull/55/commits/d3c6415939ba39affc2900d807aa28f93e8e9ccb

Same issue we were running into with Totara by the looks of it?

**Comment by aspark21** [comment]
@sarahjcotton I tested with that (latest master branch for this plugin & then tested https://github.com/aspark21/moodle-local_aws/commits/sdk-update )

Sounds like these 2 need the same treatment? - https://github.com/catalyst/moodle-local_aws/blob/master/sdk/aws-autoloader.php#L1811-L1812

**Comment by sarahjcotton** [comment]
PHPUnit errors fixed and PR created.

**Comment by aspark21** [comment]
This is still an issue with the updated master branch.

![Screenshot 2023-07-31 at 11 34 32](https://github.com/catalyst/moodle-local_aws/assets/4015496/508f0b20-7827-4b7e-b058-f2a2ecdc3905)

**Comment by aspark21** [comment]
@srdjan-catalyst - you accidentally reverted https://github.com/catalyst/moodle-local_aws/commit/d3c6415939ba39affc2900d807aa28f93e8e9ccb as part of the sdk update

**Comment by aspark21** [comment]
and the switch from require to require_once which was documented - https://github.com/catalyst/moodle-local_aws/blob/0cd13cf00014dfc80af23cff359c9e51d34ca268/sdk/readme_moodle.txt#L12

wasn't applied & documentation deleted

**Comment by hiphopservers** [comment]
I hae having the same issue after upgrading to 4.2.2

`
Error
Exception - Undefined constant GuzzleHttp\Client::VERSION
URL: https://www.nursingeducation101.com/moodle/course/modedit.php?add=resource&type&course=8&section=0&return=0&sr=0&beforemod=0
Debug info: Error code: generalexceptionmessage
Stack trace:
* line 136 of /local/aws/sdk/GuzzleHttp/functions.php: Error thrown
* line 40 of /local/aws/sdk/Aws/Handler/GuzzleV6/GuzzleHandler.php: call to GuzzleHttp\default_user_agent()
* line 87 of /local/aws/sdk/Aws/WrappedHttpHandler.php: call to Aws\Handler\GuzzleV6\GuzzleHandler->__invoke()
* line 126 of /local/aws/sdk/Aws/ClientSideMonitoring/AbstractMonitoringMiddleware.php: call to Aws\WrappedHttpHandler->__invoke()
* line 43 of /local/aws/sdk/Aws/S3/PermanentRedirectMiddleware.php: call to Aws\ClientSideMonitoring\AbstractMonitoringMiddleware->__invoke()
* line 41 of /local/aws/sdk/Aws/S3/PutObjectUrlMiddleware.php: call to Aws\S3\PermanentRedirectMiddleware->__invoke()
* line 126 of /local/aws/sdk/Aws/Middleware.php: call to Aws\S3\PutObjectUrlMiddleware->__invoke()
* line 41 of /lib/guzzlehttp/promises/src/FulfilledPromise.php: call to Aws\Middleware::Aws\{closure}()
* line 48 of /lib/guzzlehttp/promises/src/TaskQueue.php: call to GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
* line 248 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\TaskQueue->run()
* line 224 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitFn()
* line 269 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
* line 226 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->invokeWaitList()
* line 62 of /lib/guzzlehttp/promises/src/Promise.php: call to GuzzleHttp\Promise\Promise->waitIfPending()
* line 58 of /local/aws/sdk/Aws/AwsClientTrait.php: call to GuzzleHttp\Promise\Promise->wait()
* line 86 of /local/aws/sdk/Aws/AwsClientTrait.php: call to Aws\AwsClient->execute()
* line 66 of /repository/s3bucket/lib.php: call to Aws\AwsClient->__call()
* line 102 of /repository/repository_ajax.php: call to repository_s3bucket->get_listing()`

Is there an ETA on the update release for the current version of Moodle?

**Comment by zishanj** [comment]
Librelambda is also affected by this issue. Kindly fix it.

**Comment by golenkovm** [comment]
Hi all,

Just faced this issue during Moodle 4.0-4.2 upgrade. I did some digging and as I can see this is basically because of https://tracker.moodle.org/browse/MDL-76135 that landed Moodle 4.2. It brought GuzzleHttp 7 into Moodle core and it looks like it gets loaded first instead of local_aws' one which is GuzzleHttp 6.5.5. So when `GuzzleHttp\Client` is called in `line 136 of /local/aws/sdk/GuzzleHttp/functions.php` it is the core GuzzleHttp\Client which doesn't have `VERSION` constant. It doesn't look like this could be fixed by tweaking the `/local/aws/sdk/aws-autoloader.php`.

I upgraded the SDK up to 3.283.13 which has GuzzleHttp 7 in it and it seems to resolve the issue. Ideally, GuzzleHttp is not needed anymore in `local_aws` but I'm not sure if this is feasible as we still need the other bits of the SDK. Anyway, as long as the plugin GuzzleHttp matches the core GuzzleHttp we should be good.

I've created a dev 4.2 branch for this, please see https://github.com/catalyst/moodle-local_aws/commits/4.2-dev . I assume we'll need to set up a new stable branch for 4.2 onwards as @brendanheywood suggested above.

Will keep you posted on how my upgrade goes, but it's looking promising so far.

Cheers,
Misha

**Comment by Vashkatsi** [comment]
@golenkovm any info on release dates for your PR?

**Comment by golenkovm** [comment]
Hi @Vashkatsi 

The changes from #67 are looking very promising in 4.2 env. It's been under QA in non-Prod env for a month and no issues have been reported. I would still prefer to wait when it goes live (this week).

Since MDL-76135 is in 4.2 onwards I don't think #67 would work correctly in older Moodle versions so I reckon #67 will need to be closed and a `MOODLE_402_STABLE` will need to be created from `4.2-dev`.

Cheers,
Misha

**Comment by golenkovm** [comment]
Hey @marxjohnson and @sarahjcotton 

Thanks for merging the patch for this issue. I tested the patch in our upgraded 4.2 env and it looks like it's working as expected. However, there are a few concerns that I would want to mention:

1. There was a file `sdk/readme_moodle.txt` with instructions on how to update SDK. It also had required bash commands to customize the autoloader script `sdk/aws-autoloader.php`. Since the autoloader was customized more we should either update bash commands in `sdk/readme_moodle.txt` or add manual steps to update `sdk/aws-autoloader.php`. Otherwise, the changes from this PR will be wiped out during the next SDK update.

2. It was mentioned here that `if ($CFG->branch >= 402 || file_exists($CFG->dirroot. '/lib/guzzlehttp/guzzle/src/functions_include.php')) {` condition didn't work as expected during upgrade. I can see that `/GuzzleHttp/functions_include.php` file is listed here https://github.com/catalyst/moodle-local_aws/blob/master/sdk/aws-autoloader.php#L2752 . Thus it gets loaded here https://github.com/catalyst/moodle-local_aws/blob/master/sdk/aws-autoloader.php#L2827 . So when it comes to https://github.com/catalyst/moodle-local_aws/blob/master/sdk/aws-autoloader.php#L2836, the `/GuzzleHttp/functions_include.php` file is already loaded. It's a bit weird that it doesn't fail constantly.

I'd suggets to merge #70 and then work out the SDK upgrade procedure. The next upgrade will bump the guzzlehttp version and will align it with Moodle 4.2 onwards so the patch implemented as part of this PR may not be needed anymore. However, we might need to test  new SDk with older Moodle versions and cut a new branch if something won't work.

Cheers,
Misha
